# This is a basic workflow to help you get started with Actions

name: CI for RustyMage Public Splash

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # Deployment Steps
  deploy:
    runs-on: ubutnu-latest
    steps:
      - name: Deploying RustyMage to OVH Ubuntu 
        uses: appleboy/ssh-action@master # An action made to control Linux servers. 
        with: # Set all of our secrets here for the action, these won't be show bc we use "Secrets"
          host: ${{ secrets.HOST }}
          username: ${{ secrests.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/RustyMageSplash 
            git pull 
  # cd - move to the correct directory
  # git pull - pull any changes from git
