# This is a basic workflow to help you get started with Actions

name: CI for RustyMage Public Splash

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # Deployment Steps
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploying RustyMage to OVH Ubuntu 
        uses: appleboy/ssh-action@master # An action made to control Linux servers. 
        with: # Set all of our secrets here for the action, these won't be show bc we use "Secrets"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            rm -r /var/www/html/master
            cd /var/www/html/
            git branch --set-upstream-to=ospf2fullstack/rustymage main
  # cd - move to the correct directory
  # git pull - pull any changes from git